{
 "title": "ReproAPI",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP-REQUESTS-TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP-RESPONSE-TIME",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_response_time_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User_Registration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_registration_total{status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}